### ISSUE TITLE
Possible elm.json stale dependency

### ISSUE THREAD

**Issue by kczulko** [anmolitor/elm-protoc-utils#1]
Shall [this](https://github.com/anmolitor/elm-protoc-utils/blob/45d1f838513b5724ed0f5a31e9168e073868bf7d/elm.json#L23) be anmolitor/protoc-gen-elm  ?

**Comment by anmolitor** [comment]
I think elm-protocol-buffers is needed for the Utils for the Int64 type:
https://github.com/anmolitor/elm-protoc-utils/blob/45d1f838513b5724ed0f5a31e9168e073868bf7d/src/Protobuf/Utils/Int64.elm

For comparison: https://package.elm-lang.org/packages/eriktim/elm-protocol-buffers/latest/Protobuf-Types-Int64

**Comment by kczulko** [comment]
Oh... sorry, my mistake.

I thought about your fork of elm-protocol-buffers, but yes... it's a fork. Thanks for the answer!
